### ISSUE TITLE
Order of operations issue in lapic_write

### ISSUE THREAD

**Issue by PoisonNinja** [dbittman/seakernel#44]
Hi,

I was using your APIC code as a base for APIC support in my OS, but it didn't work. I ended up using a different implementation, but I noticed a issue in your order of operations in the lapic_write function.

In Line 31 of apic.c for x86_64, the code is

``` C
*((uint32_t *)lapic_addr + reg + PHYS_PAGE_MAP) = data;
```

However, that would end up casting lapic_addr to a uint32_t pointer, then add reg and PHYS_PAGE_MAP, giving the completely wrong address to set data for. The correct order would be to enclose lapic_addr + reg + PHYS_PAGE_MAP in parentheses:

``` C
*((uint32_t *)(lapic_addr + reg + PHYS_PAGE_MAP)) = data;
```

This gives the correct address. That's why for me, sending a EOI to the LAPIC didn't do anything, because I was writing to the wrong address. If you are having issues getting IOAPIC to work, this could be the culprit.

Funny thing is, the lapic_read function is correct, so it shouldn't have any issues.

**Comment by dbittman** [comment]
Yes, you are correct. I ended up using a different function to write to lapic registers (LAPIC_WRITE) which had the correct casting. I meant to delete this function, but I suppose I forgot to. Sorry for the confusion.

(I have a kernel implementation on a private repo that is going to replace this one shortly, which has much cleaner code and styles).

**Comment by PoisonNinja** [comment]
Haha no problem.
